package com.family.mealplanner.ui.theme

import androidx.compose.ui.graphics.Color

// ---- Light (warm greige neutrals, curry-leaf green primary, turmeric tertiary) ----
val LightPrimary = Color(0xFF2F6B4F)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB7EEC9)
val LightOnPrimaryContainer = Color(0xFF00210F)
val LightSecondary = Color(0xFF4E6355)
val LightSecondaryContainer = Color(0xFFDCE8DA)
val LightOnSecondaryContainer = Color(0xFF0D1F14)
val LightTertiary = Color(0xFF9A5B00)
val LightTertiaryContainer = Color(0xFFFBE0BC)
val LightOnTertiaryContainer = Color(0xFF2E1600)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD5)
val LightBackground = Color(0xFFFAF7F3)
val LightSurface = Color(0xFFFAF7F3)
val LightSurfaceVariant = Color(0xFFEAE3DA)
val LightOnSurface = Color(0xFF221F1B)
val LightOnSurfaceVariant = Color(0xFF5C554D)
val LightOutline = Color(0xFFA79E93)

// ---- Dark (warm) ----
val DarkPrimary = Color(0xFF7FD3A2)
val DarkOnPrimary = Color(0xFF00391E)
val DarkPrimaryContainer = Color(0xFF125230)
val DarkOnPrimaryContainer = Color(0xFF9CF0BE)
val DarkSecondary = Color(0xFFB5CCBB)
val DarkSecondaryContainer = Color(0xFF37493C)
val DarkOnSecondaryContainer = Color(0xFFD2E8D5)
val DarkTertiary = Color(0xFFFFB95C)
val DarkTertiaryContainer = Color(0xFF734300)
val DarkOnTertiaryContainer = Color(0xFFFFDDB6)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkBackground = Color(0xFF141210)
val DarkSurface = Color(0xFF141210)
val DarkSurfaceVariant = Color(0xFF45483F)
val DarkOnSurface = Color(0xFFECE7E0)
val DarkOnSurfaceVariant = Color(0xFFB7AFA4)
val DarkOutline = Color(0xFF8A8175)
